name: rest-api
services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure
    links: 
      - postgres
      
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: restapi
      POSTGRES_PASSWORD: restapi
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata:
